// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5ziu5oh5bvga5kdixb5olf33qq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-s4smfdet5nhxjiqyrrzjw36xja"
};


export default awsmobile;
