// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hrolbskffrdwni3iozjd67mswq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4kl25btkrnhw3pyqc6ar54ax6u",
    "aws_cognito_identity_pool_id": "us-east-1:83bd98d6-77f1-4709-9d13-bef40c9b38d5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8J6JLRnXF",
    "aws_user_pools_web_client_id": "7lp57obb5dbfncrgm94fflhqou",
    "aws_user_files_s3_bucket": "project-box2de8084f4c424ccd9c9ecd1b4ffcdbc3-master",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
